/* Synthetic sample session for the Replay Player example.
 *
 * Generated by hand to demonstrate every sample kind the draft CoreRecorder
 * understands. Timestamps are spaced so the recording lasts ~6 s when played
 * at 1×. Values are plausible but NOT taken from a real walk.
 *
 * Schema: matches CoreRecorder.SCHEMA_VERSION = "0.0.1-draft" (js/CoreRecorder.js).
 */

(function () {
    'use strict';

    var SAMPLE_SESSION = {
        schema: '0.0.1-draft',
        session: 'synthetic-walk',
        startMs: 0,
        endMs: 6000,
        durationMs: 6000,
        meta: {
            origin: 'synthetic',
            description: 'Hand-authored sample. Not a real walk. Safe to ship and replay without hardware.',
            device: 'left-instep (mock)',
        },
        sampleCount: 0, // populated below
        samples: [],
    };

    var samples = SAMPLE_SESSION.samples;
    var t = 0;

    // 12 strides of "walking" with periodic gait events and a CMJ-like burst.
    // Acc samples land every 50 ms (~20 Hz) for the first 4 s.
    for (var i = 0; i < 80; i++) {
        var phase = (i % 20) / 20; // 0..1 over a step
        // Vertical acc oscillates ~0.7 G to ~1.6 G during walking (synthetic).
        var z = 1.0 + 0.3 * Math.sin(2 * Math.PI * phase);
        var x = 0.05 * Math.sin(4 * Math.PI * phase);
        var y = 0.05 * Math.cos(2 * Math.PI * phase);
        samples.push({ t_relative_ms: t, kind: 'acc', payload: { x: +x.toFixed(3), y: +y.toFixed(3), z: +z.toFixed(3) } });
        t += 50;
    }

    // Step events at ~480 ms cadence (~125 steps/min).
    for (var s = 0; s < 8; s++) {
        var ts = 240 + s * 480;
        samples.push({
            t_relative_ms: ts,
            kind: 'gait',
            payload: {
                steps: 1,
                direction: 2, // forward
                distance: 0.7,
                calorie: 0.05,
                standing_phase_duration: 0.55,
                swing_phase_duration: 0.45,
                type: 1,
            },
        });
        samples.push({
            t_relative_ms: ts + 5,
            kind: 'stride',
            payload: { x: 0.7, y: 0.04, z: 0.0, steps_number: s + 1 },
        });
        samples.push({
            t_relative_ms: ts + 10,
            kind: 'pronation',
            payload: { x: 0.1, y: -0.05, z: 0.02 },
        });
        samples.push({
            t_relative_ms: ts + 15,
            kind: 'landingImpact',
            payload: { value: 1.2 + s * 0.05 },
        });
        samples.push({
            t_relative_ms: ts + 20,
            kind: 'footAngle',
            payload: { value: 18 + s },
        });
        samples.push({
            t_relative_ms: ts + 25,
            kind: 'stepsNumber',
            payload: { value: s + 1 },
        });
    }

    // Synthetic CMJ window: a low-G dip then a 5 G landing peak between 4.5 s
    // and 4.9 s. CoreAnalytics.feedAcc detects this as one CMJ event.
    samples.push({ t_relative_ms: 4500, kind: 'acc', payload: { x: 0.0, y: 0.0, z: 0.3 } });
    samples.push({ t_relative_ms: 4700, kind: 'acc', payload: { x: 0.0, y: 0.0, z: 0.4 } });
    samples.push({ t_relative_ms: 4900, kind: 'acc', payload: { x: 0.5, y: 0.0, z: 5.0 } });

    // Resume "walking" acc for another 1 s so the timeline doesn't end at the peak.
    for (var j = 0; j < 20; j++) {
        var ph = (j % 20) / 20;
        var zz = 1.0 + 0.3 * Math.sin(2 * Math.PI * ph);
        samples.push({ t_relative_ms: 5000 + j * 50, kind: 'acc', payload: { x: 0.0, y: 0.0, z: +zz.toFixed(3) } });
    }

    samples.sort(function (a, b) { return a.t_relative_ms - b.t_relative_ms; });
    SAMPLE_SESSION.sampleCount = samples.length;

    if (typeof module === 'object' && module.exports) {
        module.exports = SAMPLE_SESSION;
    } else {
        window.SAMPLE_SESSION = SAMPLE_SESSION;
    }
}());
